### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by artlantis** [ecomfe/fontmin-app#1]
Hi,

I would like to translate the fontmin app but I have no idea about build process. Could you please give me a sample to be able to build for win x64?

**Comment by junmer** [comment]
hi @artlantis 

Thanks for your translate.

You can build fontmin-app with [fontmin-app-builder](https://github.com/ecomfe/fontmin-app-builder) 

Usage:
1. keep `fontmin-app-builder` location as same as `fontmin-app`
2. install dependencies
   
   ```
   npm install
   ```
3. build
   
   ```
   node build.js
   ```

**Comment by artlantis** [comment]
thanks @junmer
