### ISSUE TITLE
macOS 10.12.3 生成字体失败 Error: EROFS: read-only file system, mkdir '/private/var/folders

### ISSUE THREAD

**Issue by nanxiaobei** [ecomfe/fontmin-app#10]
如图 http://wx3.sinaimg.cn/large/6645a88fly1fdqbm9i5vjj20nc0a8ju8.jpg

Error: EROFS: read-only file system, mkdir '/private/var/folders/vp/5__rgtkj1gj10ghqx5204cr40000gn/T/AppTranslocation/8584AE65-5F6F-40E6-BDE2-181E9CE22D14/d/Fontmin.app/Contents/Resources/app.nw/dist/SentyZHAO_1489769373744'

**Comment by notzheng** [comment]
尝试将 app 移动到应用程序文件夹下。

**Comment by FaceChan** [comment]
> 尝试将 app 移动到应用程序文件夹下。

同样问题。在应用程序目录一样

**Comment by vbigbang** [comment]
将 app 拷贝 到 _应用程序_ 文件夹 下。即可解决问题。注意是**【拷贝】**

**Comment by water0601** [comment]
我放在应用程序目录下可以了
