### ISSUE TITLE
RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by c9n** [ecomfe/fontmin-app#2]
RangeError: Offset is outside the bounds of the DataView

![screenshot](https://cloud.githubusercontent.com/assets/6159817/7387257/446114e2-ee8e-11e4-9a61-878e62233860.png)

**Comment by junmer** [comment]
hi @c9n , 可以把字体文件给我一下么，我定位一下问题
可以贴下网盘地址
:smiley:

**Comment by c9n** [comment]
Here u r. http://pan.baidu.com/s/1kT1PruB

**Comment by c9n** [comment]
@junmer 看了么 😄

**Comment by junmer** [comment]
@c9n app 确实有问题， 着急的话 先用 [命令行](https://github.com/ecomfe/fontmin#cli) :smiley: 
我再看看 哈

**Comment by c9n** [comment]
@junmer 好哒

**Comment by c9n** [comment]
@junmer 

``` shell
text=`curl localhost:4000 | html-to-text` && fontmin -t '$text' ~/Downloads/test.ttf

# error read glyf coordinates:4477598
```

命令行碰到了上述错误，难道是字体解析的问题么

test.ttf 就是网盘里的字体

**Comment by junmer** [comment]
@c9n 先确认一下，你的fontmin 是哪个版本？

**Comment by c9n** [comment]
@junmer 0.8.0

**Comment by c9n** [comment]
@junmer https://github.com/kekee000/fonteditor-ttf/blob/deaa68a3ad8bb291643c73b550dad3a867cd6c80/lib/ttf/table/glyf/parse.js#L13

应该是这个问题

**Comment by c9n** [comment]
把 `MAX_NUMBER_OF_COORDINATES` 改大之后，使用命令行操作就会碰到如下提示了：

``` text
Offset is outside the bounds of the DataView
```

**Comment by junmer** [comment]
@c9n hey

```
error read glyf coordinates:4477598
```

这个是个 warning , 是某个字形 有问题
应该不影响最后输出

**Comment by c9n** [comment]
@junmer 请教一下，`glyf coordinates` 是什么，这块儿不懂

**Comment by sweatyc** [comment]
仍然存在這問題，但我可以先用fontmin CLI生成一個較大的字庫後，再拉到fontmin-app就可以了

```
> fontmin myfont.ttf > myfont-raw.ttf
```
